### ISSUE TITLE
Öffnungswinkel speichern

### ISSUE THREAD

**Issue by jokuder** [ClemensGruber/hani-mandl#24]
Der zuletzt über den Drehgeber eingestellte Öffnungswinkel wird aktuell (V0.2.9) nicht abgespeichert. 

Ein sinnvoller Workflow wäre, in den Servoeinstellungen die geometrischen Anschläge zu hinterlegen, und mit dem Drehregler "zur Laufzeit" / zur Abfüllzeit den passenden Öffnungswinkel anzupassen - abhängig von Honigsorte, Temperatur, Füllstand.

**Comment by andreash-esp** [comment]
Behoben in der aktuellen develop-Version.
