### ISSUE TITLE
Make wiring compatible for the WiF LoRa 32 also 

### ISSUE THREAD

**Issue by ClemensGruber** [ClemensGruber/hani-mandl#4]
The Heltec WiF LoRa 32 is, beside the WiFi only version, a widespread board. So it may be that people have this laying around and want to use is also for the HaniMandl. Check used pins to get not in conflict with the already used pins for LoRa.

**Comment by ImkereiWetzel** [comment]
Done

**Comment by ClemensGruber** [comment]
see also https://github.com/ClemensGruber/hani-mandl/pull/15
